Feature/cris 10233 setup launch files for rp lidar
cognicept-admin/rplidar_ros pull request #1
Opened 2023-05-26 08:33 UTC by arwinder-jaspal

2023-05-30 08:12 UTC, swaroophs requested changes
Just had 1 comment. Looks great otherwise.

2023-05-30 08:12 UTC, swaroophs commented on runtime.env
Let's not include the actual IP addresses for security reasons.

2023-05-31 10:37 UTC, arwinder-jaspal commented on runtime.env
updated the IP to use the same subnet as rplidar default ip

2023-06-05 04:44 UTC, swaroophs approved these changes

2023-06-06 04:51 UTC, merged